+TITLE:   Hazel's DOOM Emacs configuration
#+AUTHOR:  Hazel Levine
#+EMAIL:   rose.hazel@protonmail.ch
#+STARTUP: nofold

Whee, literate programming, whoo. I get to type words here. These are words on a
screen. Typing. With /haaaaaaands/.

In this file, we tangle the following:
#+BEGIN_SRC emacs-lisp
;;; config.el -*- lexical-binding: t -*-
#+END_SRC
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
;;; packages.el -*- lexical-binding: t -*-
#+END_SRC

Any calls to =package!= generally get tangled to =packages.el=, whereas
everything else goes to =config.el=.

* Introduction
** =whoami=
I'm a bunny.
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Hazel Levine"
      user-mail-address "hazel@knightsofthelambdacalcul.us")
#+END_SRC
* UI
** Fonts
I've had font rendering issues with Emacs for /years/, ever since I picked it
up. Namely, Emacs' font always looked just different enough from that of
whatever terminal emulator I'm using to be annoying. Thankfully, [[https://github.com/rocx/.emacs.d][rocx's emacs
config]] held the solution by forcing Emacs to use XFT.

I first define a function to create an XFT font string from whatever font, size,
and options I want:
#+BEGIN_SRC emacs-lisp
(defun hzl/xft-font-string (name size &optional properties)
  ;; https://keithp.com/~keithp/render/Xft.tutorial
  (concat (format "%s-%d" name size)
          (when properties
            (apply #'concat (mapcar (lambda (prop)
                                      (format ":%s=%s" (car prop) (cdr prop)))
                                    properties)))))
#+END_SRC

As my university education dragged on and I began to do things with formal logic,
I needed a font with good support for unicode characters. Right now that's [[https://github.com/cormullion/juliamono][Julia
Mono]]. I use the [[https://www.ibm.com/plex/][IBM Plex]] fonts for variable pitch. I used to use IBM Plex Mono,
but it doesn't format some things properly...

I've also disabled bold fonts because I cannot get them to render properly in
Emacs.
#+BEGIN_SRC emacs-lisp
(defvar hzl/monospace-font
  (hzl/xft-font-string "Julia Mono" 10
                       '((hintstyle . 3)
                         (hinting . true)
                         (lcdfilter . 3)
                         (antialias . true))))
(defvar hzl/variable-pitch-font
  (hzl/xft-font-string "IBM Plex Sans" 10
                       '((hintstyle . 3)
                         (autohint . true)
                         (lcdfilter . 3)
                         (antialias . true))))

(setq doom-font hzl/monospace-font)
(setq doom-variable-pitch-font hzl/variable-pitch-font)
(setq doom-unicode-font hzl/monospace-font)
(setq doom-themes-enable-bold nil)
#+END_SRC
** Colorscheme
I've been using [[https://github.com/morhetz/gruvbox][Gruvbox]] Light recently. After years and years of dark themes, I
came to the realization that:
+ Anti-aliasing algorithms were better with black text on a white background
+ I can read light themes without glasses
+ "Burning your eyes" is not a thing that actually happens
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-gruvbox-light)
#+END_SRC
** Everything else
Enable line numbers, because those are nice, and make 'em relative:
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
#+END_SRC

Set the startup screen image to something comfy:
#+BEGIN_SRC emacs-lisp
(setq fancy-splash-image (concat doom-private-dir "nice.png"))
#+END_SRC
* Functionality
For the most part, DOOM Emacs handles 99% of the things I want to do in a text
editor and more, which is why this section is pretty brief.
Pretty much all of the functions I write end up under the "namespace"
=hzl/whatever=, on the merit that I want to avoid any clashes anywhere.
** MPDel music player
I usually use =ncmpcpp= for music, but sometimes when I'm working I use this.
It's all MPD, so it's not like they conflict.

We grab both MPDel and its Ivy interface:
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(package! mpdel)
(package! ivy-mpdel)
#+END_SRC

We also disable evil in MPDel because its keybindings are contingent on doing
so.
#+BEGIN_SRC emacs-lisp
(use-package! mpdel
  :config
  (mpdel-mode)
  (set-evil-initial-state! '(mpdel-playlist-mode
                             mpdel-browser-mode
                             mpdel-song-mode
                             mpdel-tablist-mode)
    'emacs))
#+END_SRC

** Arbitrary Unicode input
While I like Agda's input mode for Unicode input, it's not practical everywhere,
and I occasionally need to put Unicode into non-Agda files (namely Racket when
writing DSLs using Unicode characters). DrRacket's approach is pretty good, so I
stole a package to emulate it.
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(package! dr-racket-like-unicode
  :recipe (:host github :repo "david-christiansen/dr-racket-like-unicode"))
#+END_SRC

Bind it to C-\ everywhere, because I haven't found any situation where this
breaks anything:
#+BEGIN_SRC emacs-lisp
(use-package! dr-racket-like-unicode
  :config (map! :i "C-\\" #'dr-racket-like-unicode-char))
#+END_SRC
** LSP
Mostly handled by DOOM modules, but this causes Emacs to not fucking crash:
#+BEGIN_SRC emacs-lisp
(after! lsp-mode (setq lsp-enable-file-watchers nil))
#+END_SRC
* Productivity, papers, etc
For the boring stuff that's not /quite/ programming.
** TeXcount
This is a binding to a Perl script installed via =tlmgr= that... counts words.
Considering most of the papers I write have hard minimum/maximum limits, this
comes in pretty useful pretty often.
#+BEGIN_SRC emacs-lisp
(defun hzl/texcount ()
  ;; Counts words in a TeX file.
  (interactive)
  (let*
      ((this-file (buffer-file-name))
       (enc-str (symbol-name buffer-file-coding-system))
       (enc-opt
        (cond
         ((string-match "utf-8" enc-str) "-utf8")
         ((string-match "latin" enc-str) "-latin1")
         ("-encoding=guess")))
       (word-count
        (with-output-to-string
          (with-current-buffer standard-output
            (call-process "texcount" nil t nil "-0" enc-opt this-file)))))
    (message word-count)))
#+END_SRC

...and then, actually bind it to =C-c w= in LaTeX mode.
#+BEGIN_SRC emacs-lisp
(add-hook 'LaTeX-mode-hook (lambda () (define-key LaTeX-mode-map "\C-cw" 'hzl/texcount)))
#+END_SRC
** AucTeX =latexmk=
I use =latexmk= to build my LaTeX work because I use external files for my
bibliographies.
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(package! auctex-latexmk)
#+END_SRC

We tell it to run the auto-setup function and use PDFs:
#+BEGIN_SRC emacs-lisp
(use-package! auctex-latexmk
  :config
  (auctex-latexmk-setup)
  (setq auctex-latexmk-inherit-TeX-pdf-mode t))
#+END_SRC
** Org-mode
Set the bullets to pretty stuff:
#+BEGIN_SRC emacs-lisp
(setq org-bullets-bullet-list '("☯" "☰" "☱" "☲" "☳" "☴" "☵" "☶" "☷"))
(setq org-ellipsis "↝")
#+END_SRC

Make sure that Org doesn't try to clutter my home directory, and put stuff where
it's supposed to be:
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/usr/doc/org/")
#+END_SRC

Set DOOM's scratch buffer, available at any point with =SPC x=, to Org, which I
find useful for taking quick notes:
#+BEGIN_SRC emacs-lisp
(setq doom-scratch-buffer-major-mode 'org-mode)
#+END_SRC

We also grab =emacs-org=dnd=, for my character sheet:
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(package! ox-dnd
  :recipe (:host github :repo "xeals/emacs-org-dnd"))
#+END_SRC
#+BEGIN_SRC emacs-lisp
(use-package! ox-dnd)
#+END_SRC
** PDF Tools
While editing LaTeX documents, this is my PDF viewer of choice. Otherwise, I use
Zathura.
#+BEGIN_SRC emacs-lisp
(setq TeX-view-program-selection '((output-pdf "PDF Tools")))
(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
#+END_SRC
* Programming languages
The cool stuff. Unless it's Java.
** Agda
The Doom module is kinda broken.

Grab the executable if we can find the =agda-mode= binary:
#+BEGIN_SRC emacs-lisp
(when (executable-find "agda-mode")
  (load-file
   (let ((coding-system-for-read 'utf-8))
     (shell-command-to-string "agda-mode locate"))))
#+END_SRC

Then copy straight from the Doom Agda module:
#+BEGIN_SRC emacs-lisp
(map! :after agda2-mode
      :map agda2-mode-map
      :localleader
      "?"   #'agda2-show-goals
      "."   #'agda2-goal-and-context-and-inferred
      ","   #'agda2-goal-and-context
      "="   #'agda2-show-constraints
      "SPC" #'agda2-give
      "a"   #'agda2-auto-maybe-all
      "b"   #'agda2-previous-goal
      "c"   #'agda2-make-case
      "d"   #'agda2-infer-type-maybe-toplevel
      "e"   #'agda2-show-context
      "f"   #'agda2-next-goal
      "gG"  #'agda2-go-back
      "h"   #'agda2-helper-function-type
      "l"   #'agda2-load
      "n"   #'agda2-compute-normalised-maybe-toplevel
      "p"   #'agda2-module-contents-maybe-toplevel
      "r"   #'agda2-refine
      "s"   #'agda2-solveAll
      "t"   #'agda2-goal-type
      "w"   #'agda2-why-in-scope-maybe-toplevel
      (:prefix "x"
        "c"   #'agda2-compile
        "d"   #'agda2-remove-annotations
        "h"   #'agda2-display-implicit-arguments
        "q"   #'agda2-quit
        "r"   #'agda2-restart))
#+END_SRC
** FRC Mode
This is a =gradlew= wrapper I hacked together really fast while sitting in my
physics class not paying attention. The officially sanctioned IDE for FIRST
Robotics is Visual Studio Code, which I hate with a burning passion for numerous
reasons.

Note that I'm no longer a FRC student, so if this ever goes out of date, sucks.
I'm planning on mentoring though, so it probably won't.

We grab it directly from my Git, since it's not in ELPA (and probably never will
be):
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(package! frc-mode
  :recipe (:host nil :repo "https://git.knightsofthelambdacalcul.us/hazel/frc-mode" :branch "canon"))
#+END_SRC

And tell it to run with all Java files. I'd never willingly write Java outside
of FRC, so it's fine.
#+BEGIN_SRC emacs-lisp
(use-package! frc-mode
  :hook (java-mode . frc-mode))
#+END_SRC
** =rust-analyzer=
I have tons of issues with RLS -- it just does NOT behave. While I have to pull
=rust-analyzer= from unstable nixpkgs, and it's marked as unstable all over the
place, it's /still/ miles ahead of RLS.
#+BEGIN_SRC emacs-lisp
(after! rustic
  (setq rustic-lsp-server 'rust-analyzer))
#+END_SRC
** Scribble
The format for Racket documentation. Grab it from GitHub:
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(package! scribble-mode
  :recipe (:host github :repo "emacs-pe/scribble-mode"))
#+END_SRC

Then enable it. It takes care of the file extensions itself.
#+BEGIN_SRC emacs-lisp
(use-package! scribble-mode)
#+END_SRC

** What
#+BEGIN_SRC emacs-lisp :tangle ~/.config/doom/packages.el
(unpin! racket-mode)
(package! racket-mode
  :recipe (:host github :repo "greghendershott/racket-mode" :branch "issue-535"))
#+END_SRC
