# This was not autogenerated because of Mercurial.
# *Never ask me to touch this shit again.*
[
  {
    goPackagePath = "bitbucket.org/tshannon/config";
    fetch = {
      type = "hg";
      url = "https://bitbucket.org/tshannon/config";
      rev = "b5d2aaee93931f375346670e4440a6e18187f8b3";
      sha256 = "0rl6lsqd16a8cp4r386s842kc5h502z62yl8mi38vp5kfjxk6fji";
    };
  }
  {
    goPackagePath = "github.com/atotto/clipboard";
    fetch = {
      type = "git";
      url = "https://github.com/atotto/clipboard";
      rev = "579379fa8ff8a6d3fa979cec107f8f6d7f8fde90";
      sha256 = "0rsz70hqk8abk8isidvm7in9smhiazywjvx4f1q91annl2glav2g";
    };
  }
  {
    goPackagePath = "github.com/minio/sha256-simd";
    fetch = {
      type = "git";
      url = "https://github.com/minio/sha256-simd";
      rev = "f675151bb5e19dc10d7430bd9d4ef5e7d1b5521f";
      sha256 = "11984jaj9rq3l05nbzg3a6ravwrzbghjqa7hz7kyf8q7vqrys2df";
    };
  }
  {
    goPackagePath = "mutantmonkey.in/code/golinx";
    fetch = {
      type = "git";
      url = "https://github.com/mutantmonkey/golinx";
      rev = "04d0ad80761f1c0944262436e2426d6ab55aafa9";
      sha256 = "1hp5ym8556jmam4x75xwvsdfdghggij4k220zc95595w441sv7c3";
    };
  }
]
