let
  sources = import ../nix/sources.nix;
in
[
  {
    goPackagePath = "bitbucket.org/tshannon/config";
    fetch = {
      type = "hg"; # this is the sole reason this file isn't autogenerated
      url = "https://bitbucket.org/tshannon/config";
      rev = "b5d2aaee93931f375346670e4440a6e18187f8b3";
      sha256 = "0rl6lsqd16a8cp4r386s842kc5h502z62yl8mi38vp5kfjxk6fji";
    };
  }
  {
    goPackagePath = "github.com/atotto/clipboard";
    fetch = with sources.clipboard; {
      type = "git";
      url = "https://github.com/atotto/clipboard";
      inherit rev sha256;
    };
  }
  {
    goPackagePath = "github.com/minio/sha256-simd";
    fetch = with sources.sha256-simd; {
      type = "git";
      url = "https://github.com/minio/sha256-simd";
      inherit rev sha256;
    };
  }
  {
    goPackagePath = "mutantmonkey.in/code/golinx";
    fetch = with sources.golinx; {
      type = "git";
      url = "https://github.com/mutantmonkey/golinx";
      inherit rev sha256;
    };
  }
]
